// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpX88fKOCz6d9X9AwMnxgwWeyN4zn7uVA',
    appId: '1:300219062368:web:c35c41b0a5a2cc35f44b05',
    messagingSenderId: '300219062368',
    projectId: 'handytrust',
    authDomain: 'handytrust.firebaseapp.com',
    storageBucket: 'handytrust.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDSSoYorameSPLEmGe62WeO9c4Y8Q5JDg',
    appId: '1:300219062368:android:93351eddb2b2634ef44b05',
    messagingSenderId: '300219062368',
    projectId: 'handytrust',
    storageBucket: 'handytrust.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR8cKj0P6GJzTeW8FZcs7fnSJOUxzteYE',
    appId: '1:300219062368:ios:7d139f77e0a9d0f8f44b05',
    messagingSenderId: '300219062368',
    projectId: 'handytrust',
    storageBucket: 'handytrust.firebasestorage.app',
    iosClientId: '300219062368-7dn9b2qlqmui1o1anit12fvqs93hja87.apps.googleusercontent.com',
    iosBundleId: 'com.example.handyTrust',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR8cKj0P6GJzTeW8FZcs7fnSJOUxzteYE',
    appId: '1:300219062368:ios:7d139f77e0a9d0f8f44b05',
    messagingSenderId: '300219062368',
    projectId: 'handytrust',
    storageBucket: 'handytrust.firebasestorage.app',
    iosClientId: '300219062368-7dn9b2qlqmui1o1anit12fvqs93hja87.apps.googleusercontent.com',
    iosBundleId: 'com.example.handyTrust',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpX88fKOCz6d9X9AwMnxgwWeyN4zn7uVA',
    appId: '1:300219062368:web:ecb4f9aca8e52b7ff44b05',
    messagingSenderId: '300219062368',
    projectId: 'handytrust',
    authDomain: 'handytrust.firebaseapp.com',
    storageBucket: 'handytrust.firebasestorage.app',
  );

}